import AccountDetail from '@/components/AccountDetail';
import AccountEdit from '@/components/AccountEdit';
import AccountLoading from '@/components/AccountLoading';
import Navbar from '@/components/Navbar';
import { getToken } from '@/Functions/getToken';
import { Logout } from '@/Functions/Logout';
import { getRequest } from '@/Functions/Requests';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import ErrorComponent from '@/components/ErrorComponent'


const accountItem = ['My Account', 'Logout']

function account() {
    const router = useRouter();
    const [selectedItem, setSelectedItem] = useState('My Account');
    const [accountData, setAccountData] = useState();
    const [edit, setEdit] = useState({
        field: '',
        valueField: ''
    });
    const [getError, setGetError] = useState(false)

    const getAccount = async () => {
        try {
            const data = await getRequest('/api/account')
            if (data.message && data.message === 'Unauthorized') {
                router.push(Logout())
              }
            if (data.message && data.message.startsWith('Error')) {
                setGetError(true)
                setLoading(false)
                setTimeout(() => {
                    setGetError(false)
                }, 6000)
            } else {
                setAccountData(data)
            }
        } catch (error) {
            setGetError(true)
            setTimeout(() => {
                setGetError(false)
            }, 6000)
        }
    }

    useEffect(() => {
        getAccount()
    }, [])

    useEffect(() => {
        if (!getToken()) {
            router.push(Logout());
        }
    }, [])

    const handleItem = title => {
        if (title === 'Logout') {
            router.push(Logout());
        }
        else {
            setAccountData()
            getAccount();
            setSelectedItem(title)
        }
    }

    return (
        <>
            <Head>
                <title>Account - Seller</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <main className='w-100 flex flex-col box-border'>
                <Navbar />
                {getError && <ErrorComponent />}
                <div className='w-full px-2 md:px-4 gap-4 pb-10 mt-20 flex flex-col md:flex-row'>
                    <div className='w-full md:w-1/4'>
                        <div className='w-full flex gap-4 flex-row md:flex-col'>
                            {accountItem.map((e, i) => {
                                return (
                                    <button onClick={() => handleItem(e)} key={`accountItem-${i}`} className={`p-3 rounded-md text-sm shadow-lg font-medium ${selectedItem === e ? 'text-white bg-red-500' : 'text-black'}`}>{e}</button>
                                )
                            })}
                        </div>
                    </div>
                    <div className='w-full gap-3 md:w-3/4 justify-start items-center flex flex-col'>
                        <span className='text-xl font-medium'>{selectedItem}</span>
                        {selectedItem === 'My Account' && accountData ?
                            <div className='w-full px-1 md:w-11/12 flex flex-col'>
                                <AccountDetail setEdit={setEdit} title='Display Name' value={accountData.displayName} valueField='displayName' className='border-2 rounded-tl-lg rounded-tr-lg' />
                                <AccountDetail setEdit={setEdit} title='Name' value={accountData.name} valueField='name' className='border-2 border-t-0' />
                                <AccountDetail setEdit={setEdit} title='E-mail' value={accountData.email} valueField='email' className='border-2 border-t-0' />
                                <AccountDetail setEdit={setEdit} title='Mobile Number' value={accountData.number} valueField='number' className='border-2 border-t-0' />
                                <AccountDetail setEdit={setEdit} title='Address' value={accountData.address} valueField='address' className='border-2 rounded-bl-lg border-t-0 rounded-br-lg' />
                                {edit.field && <AccountEdit getAccount={getAccount} setEdit={setEdit} edit={edit} accountData={accountData} />}
                            </div>
                            : selectedItem === 'My Account' && <AccountLoading />
                        }
                    </div>

                </div>
            </main>
        </>

    )
}

export default account;