import Navbar from '../components/Navbar'
import Head from 'next/head'
import Input from '@/components/Input'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import Loading from '@/components/Loading'
import { useRouter } from 'next/router'
import { getToken } from '@/Functions/getToken'
import ErrorComponent from '@/components/ErrorComponent'


export default function Home() {
    const router = useRouter()
    const [getError, setGetError] = useState(false)
    const [loading, setLoading] = useState(true)

    useEffect(() => {
        if(!getToken()) {
            router.push('/')
        }
    }, [])

    return (
        <>
            <Head>
                <title>Seller - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <main className='w-100 flex flex-col'>
                <Navbar />
                {getError && <ErrorComponent />}
                <div className='w-full bg-white gap-4 pb-10 mt-20 flex flex-col'>
                    
                </div>
                {loading && <Loading />}
            </main>
        </>
    )
}